export const products = [
  {
    id: 1,
    name: 'Velvet Midi Dress',
    price: 68,
    category: 'Dresses',
    image: 'https://images.unsplash.com/photo-1520975910055-4a8c892001d3?auto=format&fit=crop&w=900&q=80',
    description: 'A feminine midi dress with soft velvet texture and a flattering silhouette.',
    tags: ['new', 'limited'],
  },
  {
    id: 2,
    name: 'Leather Crossbody Bag',
    price: 98,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
    description: 'A contemporary crossbody with polished hardware and rich leather finish.',
    tags: ['bestseller'],
  },
  {
    id: 3,
    name: 'Tailored Blazer',
    price: 120,
    category: 'Outerwear',
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
    description: 'A structured blazer designed with clean lines for a modern professional look.',
    tags: ['classic', 'sale'],
  },
  {
    id: 4,
    name: 'Silk Scarf',
    price: 32,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80',
    description: 'An elegant silk scarf perfect for styling any outfit with subtle color accents.',
    tags: ['new'],
  },
  {
    id: 5,
    name: 'High Waist Jeans',
    price: 74,
    category: 'Bottoms',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80',
    description: 'Textured denim with a flattering high waist and comfortable stretch.',
    tags: ['popular'],
  },
];
